apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base-manifest

commonAnnotations:
  app.zerodt.com/version: before-native-sidecar-v2


patches:
# - path: deployment-patch.yaml
#   target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: web-pool
- path: pdb-patch.yaml
  target:
    group: policy
    version: v1
    kind: PodDisruptionBudget
    name: web-pool
- path: rollout-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Rollout
    name: web-pool
