kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.33.4 # Kubernetes version
- role: worker
  image: kindest/node:v1.33.4
  labels:
    tier: ondemand
- role: worker
  image: kindest/node:v1.33.4
  labels:
    tier: ondemand
- role: worker
  image: kindest/node:v1.33.4
  labels:
    tier: spot
