apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-pool
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - ondemand
      tolerations:
      - effect: NoSchedule
        key: dedicated-web
        operator: Equal
        value: "true"
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.zerodt.com/component: web
            app.zerodt.com/instance: k8s
        maxSkew: 1
        # minDomains: 2
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      initContainers:
      - name: envoy
        image: envoyproxy/envoy:v1.34.6
        restartPolicy: Always
        ports:
        - containerPort: 9211
          name: envoy
          protocol: TCP
        - containerPort: 9901
          name: envoy-admin
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/envoy/
          name: envoy-config-volume
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: WEB_CONCURRENCY
          value: "1"
        image: kosarajus/monolith:v0.1.7
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8000
          name: app
          protocol: TCP
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
      hostAliases:
      - hostnames:
        - webapp
        - envoy
        ip: 127.0.0.1
      terminationGracePeriodSeconds: 600 # we have higher value for this due to nature of long running requests for certain parts of the application
      volumes:
      - name: envoy-config-volume
        configMap:
          name: k8s-envoy-config
